name: basemodels
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - tensorflow
    - keras
    - python-pptx
