name: basemodels
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pydot
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - tensorflow
    - keras
    - python-pptx
    - git+https://github.com/dagwieers/unoconv
    - PyDrive
    - fileupload
